import localFont from "next/font/local";
import { Inter, Poppins } from "@next/font/google";
import "./globals.css";
import NavDesktop from "./compontents/shared-compontents/nav-desktop";
import MobileNav from "./compontents/shared-compontents/mobile-nav";
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Solar Gard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <NavDesktop />
        </div>
        <div>
          <MobileNav />
        </div>
        {children}
      </body>
    </html>
  );
}
